// <auto-generated />
using System;
using ELodowka.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELodowka.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230412160956_Ingredients")]
    partial class Ingredients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("ELodowka.Data.Ingredients.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Marchewka",
                            Type = 0
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Pomidor",
                            Type = 0
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Cebula",
                            Type = 0
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Szynka",
                            Type = 1
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Kiełbasa śląska",
                            Type = 1
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Buraki",
                            Type = 0
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Papryka",
                            Type = 0
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Sałata",
                            Type = 0
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Ogórek",
                            Type = 0
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Ziemniaki",
                            Type = 0
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Bataty",
                            Type = 0
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Kapusta",
                            Type = 0
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Kapary",
                            Type = 0
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Dynia",
                            Type = 0
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Fasola",
                            Type = 0
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Karkówka",
                            Type = 1
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Pierś z Kurczaka",
                            Type = 1
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Salami",
                            Type = 1
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Kiełbasa Żywiecka",
                            Type = 1
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Stek Wołowy",
                            Type = 1
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Wieprzowina Mielona",
                            Type = 1
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Pierś z Kaczki",
                            Type = 1
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Bekon",
                            Type = 1
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Noga z Kurczaka",
                            Type = 1
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Pierś z Indyka",
                            Type = 1
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Mleko 2%",
                            Type = 2
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Mleko 1.5%",
                            Type = 2
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Mleko 3.2%",
                            Type = 2
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Ser Gouda",
                            Type = 2
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Ser Mozarella",
                            Type = 2
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Ser Parmezan",
                            Type = 2
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Ser Mascarponne",
                            Type = 2
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Ser Fetta",
                            Type = 2
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Maślanka",
                            Type = 2
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Masło",
                            Type = 2
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Chleb Pszenny",
                            Type = 3
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Chleb Żytni",
                            Type = 3
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Chleb Na Zakwasie",
                            Type = 3
                        },
                        new
                        {
                            Id = 39L,
                            Name = "Pumpernikiel",
                            Type = 3
                        },
                        new
                        {
                            Id = 40L,
                            Name = "Chleb Orkiszowy",
                            Type = 3
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Makaron Spaghetti",
                            Type = 4
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Makaron Pene",
                            Type = 4
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Makaron Tagiatelle",
                            Type = 4
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Sól",
                            Type = 5
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Pieprz",
                            Type = 5
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Pparyka Słodka",
                            Type = 5
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Papryka Ostra",
                            Type = 5
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Czosnek Mielony",
                            Type = 5
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Oregano",
                            Type = 5
                        },
                        new
                        {
                            Id = 50L,
                            Name = "Bazylia",
                            Type = 5
                        });
                });

            modelBuilder.Entity("ELodowka.Data.RecipeIngredients.RecipeIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("QuantityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("ELodowka.Data.Recipes.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("ELodowka.Data.Steps.Step", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("ELodowka.Data.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ELodowka.Data.RecipeIngredients.RecipeIngredient", b =>
                {
                    b.HasOne("ELodowka.Data.Ingredients.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELodowka.Data.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ELodowka.Data.Recipes.Recipe", b =>
                {
                    b.HasOne("ELodowka.Data.Users.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ELodowka.Data.Steps.Step", b =>
                {
                    b.HasOne("ELodowka.Data.Recipes.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ELodowka.Data.Ingredients.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("ELodowka.Data.Recipes.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ELodowka.Data.Users.User", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
