// <auto-generated />
using System;
using ELodowka.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELodowka.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230413172704_MoreIngredients")]
    partial class MoreIngredients
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.11");

            modelBuilder.Entity("ELodowka.Data.Ingredients.Ingredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Marchewka",
                            Type = 0
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Pomidor",
                            Type = 0
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Cebula",
                            Type = 0
                        },
                        new
                        {
                            Id = 4L,
                            Name = "Szynka",
                            Type = 1
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Kiełbasa śląska",
                            Type = 1
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Buraki",
                            Type = 0
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Papryka",
                            Type = 0
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Sałata",
                            Type = 0
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Ogórek",
                            Type = 0
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Ziemniaki",
                            Type = 0
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Bataty",
                            Type = 0
                        },
                        new
                        {
                            Id = 12L,
                            Name = "Kapusta",
                            Type = 0
                        },
                        new
                        {
                            Id = 13L,
                            Name = "Kapary",
                            Type = 0
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Dynia",
                            Type = 0
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Fasola",
                            Type = 0
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Karkówka",
                            Type = 1
                        },
                        new
                        {
                            Id = 17L,
                            Name = "Pierś z Kurczaka",
                            Type = 1
                        },
                        new
                        {
                            Id = 18L,
                            Name = "Salami",
                            Type = 1
                        },
                        new
                        {
                            Id = 19L,
                            Name = "Kiełbasa Żywiecka",
                            Type = 1
                        },
                        new
                        {
                            Id = 20L,
                            Name = "Stek Wołowy",
                            Type = 1
                        },
                        new
                        {
                            Id = 21L,
                            Name = "Wieprzowina Mielona",
                            Type = 1
                        },
                        new
                        {
                            Id = 22L,
                            Name = "Pierś z Kaczki",
                            Type = 1
                        },
                        new
                        {
                            Id = 23L,
                            Name = "Bekon",
                            Type = 1
                        },
                        new
                        {
                            Id = 24L,
                            Name = "Noga z Kurczaka",
                            Type = 1
                        },
                        new
                        {
                            Id = 25L,
                            Name = "Pierś z Indyka",
                            Type = 1
                        },
                        new
                        {
                            Id = 26L,
                            Name = "Mleko 2%",
                            Type = 2
                        },
                        new
                        {
                            Id = 27L,
                            Name = "Mleko 1.5%",
                            Type = 2
                        },
                        new
                        {
                            Id = 28L,
                            Name = "Mleko 3.2%",
                            Type = 2
                        },
                        new
                        {
                            Id = 29L,
                            Name = "Ser Gouda",
                            Type = 2
                        },
                        new
                        {
                            Id = 30L,
                            Name = "Ser Mozarella",
                            Type = 2
                        },
                        new
                        {
                            Id = 31L,
                            Name = "Ser Parmezan",
                            Type = 2
                        },
                        new
                        {
                            Id = 32L,
                            Name = "Ser Mascarponne",
                            Type = 2
                        },
                        new
                        {
                            Id = 33L,
                            Name = "Ser Fetta",
                            Type = 2
                        },
                        new
                        {
                            Id = 34L,
                            Name = "Maślanka",
                            Type = 2
                        },
                        new
                        {
                            Id = 35L,
                            Name = "Masło",
                            Type = 2
                        },
                        new
                        {
                            Id = 36L,
                            Name = "Chleb Pszenny",
                            Type = 3
                        },
                        new
                        {
                            Id = 37L,
                            Name = "Chleb Żytni",
                            Type = 3
                        },
                        new
                        {
                            Id = 38L,
                            Name = "Chleb Na Zakwasie",
                            Type = 3
                        },
                        new
                        {
                            Id = 39L,
                            Name = "Pumpernikiel",
                            Type = 3
                        },
                        new
                        {
                            Id = 40L,
                            Name = "Chleb Orkiszowy",
                            Type = 3
                        },
                        new
                        {
                            Id = 41L,
                            Name = "Makaron Spaghetti",
                            Type = 4
                        },
                        new
                        {
                            Id = 42L,
                            Name = "Makaron Pene",
                            Type = 4
                        },
                        new
                        {
                            Id = 43L,
                            Name = "Makaron Tagiatelle",
                            Type = 4
                        },
                        new
                        {
                            Id = 44L,
                            Name = "Sól",
                            Type = 5
                        },
                        new
                        {
                            Id = 45L,
                            Name = "Pieprz",
                            Type = 5
                        },
                        new
                        {
                            Id = 46L,
                            Name = "Paryka Słodka",
                            Type = 5
                        },
                        new
                        {
                            Id = 47L,
                            Name = "Papryka Ostra",
                            Type = 5
                        },
                        new
                        {
                            Id = 48L,
                            Name = "Czosnek Mielony",
                            Type = 5
                        },
                        new
                        {
                            Id = 49L,
                            Name = "Oregano",
                            Type = 5
                        },
                        new
                        {
                            Id = 50L,
                            Name = "Bazylia",
                            Type = 5
                        },
                        new
                        {
                            Id = 51L,
                            Name = "Jajka",
                            Type = 2
                        },
                        new
                        {
                            Id = 52L,
                            Name = "Cebula",
                            Type = 0
                        },
                        new
                        {
                            Id = 53L,
                            Name = "Mąka",
                            Type = 6
                        },
                        new
                        {
                            Id = 54L,
                            Name = "Cukier",
                            Type = 5
                        },
                        new
                        {
                            Id = 55L,
                            Name = "Ryż",
                            Type = 6
                        },
                        new
                        {
                            Id = 56L,
                            Name = "Keczup",
                            Type = 7
                        },
                        new
                        {
                            Id = 57L,
                            Name = "Proszek do pieczenia",
                            Type = 5
                        },
                        new
                        {
                            Id = 58L,
                            Name = "Majonez",
                            Type = 7
                        },
                        new
                        {
                            Id = 59L,
                            Name = "Śmietana",
                            Type = 7
                        },
                        new
                        {
                            Id = 60L,
                            Name = "Liść Laurowy",
                            Type = 5
                        },
                        new
                        {
                            Id = 61L,
                            Name = "Majeranek",
                            Type = 5
                        },
                        new
                        {
                            Id = 62L,
                            Name = "Cynamon",
                            Type = 5
                        },
                        new
                        {
                            Id = 63L,
                            Name = "Olej rzepakowy",
                            Type = 8
                        },
                        new
                        {
                            Id = 64L,
                            Name = "Musztarda",
                            Type = 7
                        },
                        new
                        {
                            Id = 65L,
                            Name = "Soda Oczyszczona",
                            Type = 5
                        },
                        new
                        {
                            Id = 66L,
                            Name = "Tymianek",
                            Type = 5
                        },
                        new
                        {
                            Id = 67L,
                            Name = "Miód",
                            Type = 7
                        },
                        new
                        {
                            Id = 68L,
                            Name = "Olej Słonecznikowy",
                            Type = 8
                        },
                        new
                        {
                            Id = 69L,
                            Name = "Jogurt",
                            Type = 2
                        },
                        new
                        {
                            Id = 70L,
                            Name = "Pieczarki",
                            Type = 9
                        },
                        new
                        {
                            Id = 71L,
                            Name = "Seler",
                            Type = 0
                        },
                        new
                        {
                            Id = 72L,
                            Name = "Por",
                            Type = 0
                        },
                        new
                        {
                            Id = 73L,
                            Name = "Cukinia",
                            Type = 0
                        },
                        new
                        {
                            Id = 74L,
                            Name = "Rzodkiewka",
                            Type = 0
                        },
                        new
                        {
                            Id = 75L,
                            Name = "Kalafior",
                            Type = 0
                        },
                        new
                        {
                            Id = 76L,
                            Name = "NikocadoAvokado",
                            Type = 0
                        },
                        new
                        {
                            Id = 77L,
                            Name = "Rukola",
                            Type = 0
                        },
                        new
                        {
                            Id = 78L,
                            Name = "Szparagi",
                            Type = 0
                        },
                        new
                        {
                            Id = 79L,
                            Name = "Bakłażan",
                            Type = 0
                        },
                        new
                        {
                            Id = 80L,
                            Name = "Kalarepa",
                            Type = 0
                        },
                        new
                        {
                            Id = 81L,
                            Name = "Bób",
                            Type = 0
                        },
                        new
                        {
                            Id = 82L,
                            Name = "Jarmuż",
                            Type = 0
                        },
                        new
                        {
                            Id = 83L,
                            Name = "Brukselka",
                            Type = 0
                        },
                        new
                        {
                            Id = 84L,
                            Name = "Podgrzybki",
                            Type = 9
                        },
                        new
                        {
                            Id = 85L,
                            Name = "Borowki",
                            Type = 9
                        },
                        new
                        {
                            Id = 86L,
                            Name = "Prawdziwki",
                            Type = 9
                        },
                        new
                        {
                            Id = 87L,
                            Name = "Boczniaki",
                            Type = 9
                        },
                        new
                        {
                            Id = 88L,
                            Name = "Rzepa",
                            Type = 0
                        },
                        new
                        {
                            Id = 89L,
                            Name = "Opieńki",
                            Type = 9
                        },
                        new
                        {
                            Id = 90L,
                            Name = "Jabłka",
                            Type = 10
                        },
                        new
                        {
                            Id = 91L,
                            Name = "Kiwi",
                            Type = 10
                        },
                        new
                        {
                            Id = 92L,
                            Name = "Cytryna",
                            Type = 10
                        },
                        new
                        {
                            Id = 93L,
                            Name = "Truskawki",
                            Type = 10
                        },
                        new
                        {
                            Id = 94L,
                            Name = "Pomarańcza",
                            Type = 10
                        },
                        new
                        {
                            Id = 95L,
                            Name = "Banan",
                            Type = 10
                        },
                        new
                        {
                            Id = 96L,
                            Name = "Śliwki",
                            Type = 10
                        },
                        new
                        {
                            Id = 97L,
                            Name = "Limonka",
                            Type = 10
                        },
                        new
                        {
                            Id = 98L,
                            Name = "Mango",
                            Type = 10
                        },
                        new
                        {
                            Id = 99L,
                            Name = "Winogron",
                            Type = 10
                        },
                        new
                        {
                            Id = 100L,
                            Name = "Morele",
                            Type = 10
                        },
                        new
                        {
                            Id = 101L,
                            Name = "Granat",
                            Type = 10
                        },
                        new
                        {
                            Id = 102L,
                            Name = "Grapefruit",
                            Type = 10
                        },
                        new
                        {
                            Id = 103L,
                            Name = "Kokos",
                            Type = 10
                        },
                        new
                        {
                            Id = 104L,
                            Name = "Arbuz",
                            Type = 10
                        },
                        new
                        {
                            Id = 105L,
                            Name = "Pitaja",
                            Type = 10
                        },
                        new
                        {
                            Id = 106L,
                            Name = "Kefir",
                            Type = 2
                        },
                        new
                        {
                            Id = 107L,
                            Name = "Serek Wiejski",
                            Type = 2
                        },
                        new
                        {
                            Id = 108L,
                            Name = "Skyr",
                            Type = 2
                        },
                        new
                        {
                            Id = 109L,
                            Name = "Ricotta",
                            Type = 2
                        },
                        new
                        {
                            Id = 110L,
                            Name = "Bita Śmietana",
                            Type = 2
                        },
                        new
                        {
                            Id = 111L,
                            Name = "Słonina",
                            Type = 1
                        },
                        new
                        {
                            Id = 112L,
                            Name = "Szynka Parmeńska",
                            Type = 1
                        },
                        new
                        {
                            Id = 113L,
                            Name = "Kabanosy",
                            Type = 1
                        },
                        new
                        {
                            Id = 114L,
                            Name = "Kaszanka",
                            Type = 1
                        },
                        new
                        {
                            Id = 115L,
                            Name = "Kiełbasa Podwawelska",
                            Type = 1
                        },
                        new
                        {
                            Id = 116L,
                            Name = "Mortadela",
                            Type = 1
                        },
                        new
                        {
                            Id = 117L,
                            Name = "Żeberka",
                            Type = 1
                        },
                        new
                        {
                            Id = 118L,
                            Name = "Serdelki",
                            Type = 1
                        },
                        new
                        {
                            Id = 119L,
                            Name = "Pasztet",
                            Type = 1
                        },
                        new
                        {
                            Id = 120L,
                            Name = "Skrzydełko Kurczaka",
                            Type = 1
                        },
                        new
                        {
                            Id = 121L,
                            Name = "Udko Kurczaka",
                            Type = 1
                        },
                        new
                        {
                            Id = 122L,
                            Name = "Schab wieprzowy",
                            Type = 1
                        },
                        new
                        {
                            Id = 123L,
                            Name = "Szyjka z indyka",
                            Type = 1
                        },
                        new
                        {
                            Id = 124L,
                            Name = "Kurze łapki",
                            Type = 1
                        },
                        new
                        {
                            Id = 125L,
                            Name = "Polędwica wieprzowa",
                            Type = 1
                        },
                        new
                        {
                            Id = 126L,
                            Name = "Mostek wieprzowy",
                            Type = 1
                        },
                        new
                        {
                            Id = 127L,
                            Name = "Antrykot",
                            Type = 1
                        },
                        new
                        {
                            Id = 128L,
                            Name = "Łopatka wieprzowa",
                            Type = 1
                        },
                        new
                        {
                            Id = 129L,
                            Name = "Goleń wieprzowa",
                            Type = 1
                        },
                        new
                        {
                            Id = 130L,
                            Name = "Filet Drobiowy",
                            Type = 1
                        },
                        new
                        {
                            Id = 131L,
                            Name = "Grzbiet Drobiowy",
                            Type = 1
                        },
                        new
                        {
                            Id = 132L,
                            Name = "Ćwiartka z Kurczaka",
                            Type = 1
                        },
                        new
                        {
                            Id = 133L,
                            Name = "Bułka tarta",
                            Type = 3
                        },
                        new
                        {
                            Id = 134L,
                            Name = "Boczek",
                            Type = 1
                        },
                        new
                        {
                            Id = 135L,
                            Name = "Mięso Mielone",
                            Type = 1
                        },
                        new
                        {
                            Id = 136L,
                            Name = "Cały kurczak",
                            Type = 1
                        },
                        new
                        {
                            Id = 137L,
                            Name = "Śledź",
                            Type = 11
                        },
                        new
                        {
                            Id = 138L,
                            Name = "Łosoś",
                            Type = 11
                        },
                        new
                        {
                            Id = 139L,
                            Name = "Tuńczyk",
                            Type = 11
                        },
                        new
                        {
                            Id = 140L,
                            Name = "Dorsz",
                            Type = 11
                        },
                        new
                        {
                            Id = 141L,
                            Name = "Dorsz",
                            Type = 11
                        },
                        new
                        {
                            Id = 142L,
                            Name = "Pstrąg",
                            Type = 11
                        },
                        new
                        {
                            Id = 143L,
                            Name = "Filety Rybne",
                            Type = 11
                        },
                        new
                        {
                            Id = 144L,
                            Name = "Krewetki",
                            Type = 11
                        },
                        new
                        {
                            Id = 145L,
                            Name = "Małże",
                            Type = 11
                        },
                        new
                        {
                            Id = 146L,
                            Name = "Kawior",
                            Type = 11
                        },
                        new
                        {
                            Id = 147L,
                            Name = "Kalmary",
                            Type = 11
                        },
                        new
                        {
                            Id = 148L,
                            Name = "Krab",
                            Type = 11
                        },
                        new
                        {
                            Id = 149L,
                            Name = "Imbir",
                            Type = 5
                        },
                        new
                        {
                            Id = 151L,
                            Name = "Ziele Angielskie",
                            Type = 5
                        },
                        new
                        {
                            Id = 152L,
                            Name = "Kminek",
                            Type = 5
                        },
                        new
                        {
                            Id = 153L,
                            Name = "Kurkuma",
                            Type = 5
                        },
                        new
                        {
                            Id = 154L,
                            Name = "Rozmaryn",
                            Type = 5
                        },
                        new
                        {
                            Id = 155L,
                            Name = "Koper",
                            Type = 5
                        },
                        new
                        {
                            Id = 156L,
                            Name = "Mięta",
                            Type = 5
                        },
                        new
                        {
                            Id = 157L,
                            Name = "Kardamon",
                            Type = 5
                        },
                        new
                        {
                            Id = 158L,
                            Name = "Gałka Muszkatołowa",
                            Type = 5
                        },
                        new
                        {
                            Id = 159L,
                            Name = "Jaskółcze ziele",
                            Type = 5
                        },
                        new
                        {
                            Id = 160L,
                            Name = "Szakłak",
                            Type = 5
                        },
                        new
                        {
                            Id = 161L,
                            Name = "Ćwikła",
                            Type = 5
                        },
                        new
                        {
                            Id = 162L,
                            Name = "Curry",
                            Type = 5
                        },
                        new
                        {
                            Id = 163L,
                            Name = "Lubczyk",
                            Type = 5
                        },
                        new
                        {
                            Id = 164L,
                            Name = "Kolendra",
                            Type = 5
                        },
                        new
                        {
                            Id = 165L,
                            Name = "Kasza",
                            Type = 6
                        },
                        new
                        {
                            Id = 166L,
                            Name = "Kakao",
                            Type = 5
                        },
                        new
                        {
                            Id = 167L,
                            Name = "Piwo",
                            Type = 3
                        },
                        new
                        {
                            Id = 168L,
                            Name = "Bulion warzywny",
                            Type = 12
                        },
                        new
                        {
                            Id = 169L,
                            Name = "bulion Drobiowy",
                            Type = 12
                        },
                        new
                        {
                            Id = 170L,
                            Name = "Zakwas",
                            Type = 12
                        },
                        new
                        {
                            Id = 171L,
                            Name = "Krasnoludzki Spirytus",
                            Type = 3
                        },
                        new
                        {
                            Id = 172L,
                            Name = "Dmuchawiec",
                            Type = 5
                        },
                        new
                        {
                            Id = 173L,
                            Name = "Mutagen z Bazyliszka",
                            Type = 12
                        },
                        new
                        {
                            Id = 174L,
                            Name = "Kwiat Dwugrotu",
                            Type = 5
                        },
                        new
                        {
                            Id = 175L,
                            Name = "Liść Blekotu",
                            Type = 5
                        });
                });

            modelBuilder.Entity("ELodowka.Data.RecipeIngredients.RecipeIngredient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<string>("QuantityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("ELodowka.Data.Recipes.Recipe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("ELodowka.Data.Steps.Step", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RecipeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("ELodowka.Data.Users.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ELodowka.Data.RecipeIngredients.RecipeIngredient", b =>
                {
                    b.HasOne("ELodowka.Data.Ingredients.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ELodowka.Data.Recipes.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ELodowka.Data.Recipes.Recipe", b =>
                {
                    b.HasOne("ELodowka.Data.Users.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ELodowka.Data.Steps.Step", b =>
                {
                    b.HasOne("ELodowka.Data.Recipes.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ELodowka.Data.Ingredients.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("ELodowka.Data.Recipes.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ELodowka.Data.Users.User", b =>
                {
                    b.Navigation("Recipes");
                });
#pragma warning restore 612, 618
        }
    }
}
